### ISSUE TITLE
User Story 2

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#1]
### Detailpage

As a user 
I want to be able to click somewhere
So that i see the details of my daily card

### Description

![Image](https://user-images.githubusercontent.com/115098194/229452070-d201ed9f-197f-4eb3-aca3-80777714aeb1.png)

### Acceptance Criteria:

- [x] The given data is displayed correctly
- [x] There is a button for “more details”

### Tasks:

- [x] code a button "more details" 
- [x] display a list that displays name, number, element, mood, action
