### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#2]
### User Story 1

As a user of the tarot app
I want to see a random tarot card
So that i know what my daily card is
### 
Description:

![Image](https://user-images.githubusercontent.com/115098194/229448666-47961681-513c-473c-9f27-47cb8f8258a9.png)

### Acceptance Criteria:

- [x] 1. A random card is displayed
- [x] 2. In a card the name is displayed
- [x] 3. In a card the number is displayed
- [x] 4. correct placeholder image is displayed
- [x] 5. no swr 

### Tasks:

- rework database to have images
- add images (just placesholders with the names of the card)
- rework whole code so it doesn't rely on swr
