### ISSUE TITLE
User Story 3

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#3]
Userstory 3

### Notizen

As a user
I want to see a blank notepage
So that i can take notes

![Image](https://user-images.githubusercontent.com/115098194/229455208-1e711cd2-92a2-40f8-8fbd-9f16e61682a8.png)

### Acceptance Criteria:

- [x] There is a textarea
- [x] Focus is set to that text-area
- [x] there is a end-button

### tasks:

- [x] create a text-area
- [x] make a button with content “end”
- [x] set focus to text-area
- [x] save the content of text-area into array 
- [x] array should contain name of the card and then the date

**Comment by manukao** [comment]
lgtm 👍
