### ISSUE TITLE
User Story 4

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#4]
### Moodmeter

As a user
I want to click on some button
So that i can show if i am in good or bad mood

### Description 

![Image](https://user-images.githubusercontent.com/115098194/229459248-e0ddd565-f196-42c2-8202-f12ebdcd3bdf.png)

### acceptance criteria:

- [x] a plus button is displayed
- [x] a minus button is displayed
- [x] after clicking plus or minus both buttons get locked

### tasks

- [x] create 2 buttons "+" and "-"
- [x] make em unclickable after making a decision
- [x] the value is saved to array "mood"
- [ ] mood-array contains card-name and mood-value
- [x] mood-value is the average of all card specific mood-values

**Comment by FrankSiyli** [comment]
LGTM

**Comment by DominicWebDev** [comment]
LGTM, works well !

**Comment by rabe200** [comment]
@DominicWebDev thanks a lot- just a hint for the code review: comment on the pull request, so the coaches see that you've also checked the code :)
