### ISSUE TITLE
User Story 5

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#5]
### Startpage

As a User i want to see a start-page
So that i can choose between modes and options

![Image](https://user-images.githubusercontent.com/115098194/229464489-4f4a305d-a610-4d6f-beb4-a803438048fc.png)

### acceptance criteria

- [x] there is a button for “tageskarte”
- [x] there is a button for “history”

### tasks
- [x] create the buttons for the pages that exist already
- [x] no dead links

**Comment by toshydev** [comment]
LGTM
