### ISSUE TITLE
User Story 6

### ISSUE THREAD

**Issue by rabe200** [rabe200/Capstone_Tarot_App#6]
### History

As a user i want to be able to look through all cards
So that i can see my notes and learn about cardmeanings

### Description

![Image](https://user-images.githubusercontent.com/115098194/229468949-df2ac1b2-2505-4e6b-9b98-a248f29c07d0.png)

### acceptance critera

- [x] the card, name ~~and number~~ are displayed
- [x] there are buttons for navigation
- [x] a button for overview 
- [x] clicking ~~the card~~ a button leads to “detailpage”

### tasks
- [x] create the slug page
- [x] each page is connected to a slug, id or another unique identifier of a single card
- [x] thus displaying the picture
- [x] clicking the picture leads to the detail-page 
- [x]  ~~render overview and search button~~
- [x] ~~create overview.js and search.js~~
- [x] get the links working
- [x] clicking the navigation buttons leads to next or previous slug. most prolly useRouter will be handy here

**Comment by toshydev** [comment]
Perfect! LGTM
